name: language_version
description: >-
  Create, parse, compare, and share Dart language versions.
version: 0.1.0
repository: https://github.com/dart-community/language_version

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  night_raven_insight: ^4.0.0
  test: ^1.26.0
